name: Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  push_to_registry:
    name: Push Docker image to Github Packages
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Github Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push the image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/my-app:latest
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME
    
    
